# Change these first
owner: M17-Project # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: M17-M17
    url: https://ref.m17.link

assignees:
  - kc1awv

status-website:
  cname: uptime.m17.link
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: M17 Uptime
  introTitle: "**M17 Uptime** is the open-source uptime monitor and status page, powered entirely by [Upptime](https://github.com/upptime/upptime) and GitHub."
  introMessage: This is the status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
